name: firstly
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

#Utility packages

 
  #state management

  

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  http: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  get: ^4.6.5
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9
  cloud_firestore: ^4.16.1
  shimmer: ^3.0.0
  skeletonizer: ^1.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  flutter_modular: ^6.3.2
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_database: ^10.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

 #---------------------- LOCAL ASSETS --------------------------------#

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    

    #---------------------- LOCAL FONTS --------------------------------#

  fonts:
   - family: Inter
     fonts:
      #  - asset: fonts/Inter-Light.ttf
      #    weight: 300
       - asset: assets/fonts/Inter-ExtraLight.ttf
         weight: 200
       - asset: assets/fonts/Inter-Thin.ttf
         weight: 100
       - asset: assets/fonts/Inter-Regular.ttf
         weight: 400
       - asset: assets/fonts/Inter-Medium.ttf
         weight: 500
       - asset: assets/fonts/Inter-Semibold.ttf
         weight: 600
       - asset: assets/fonts/Inter-Bold.ttf
         weight: 700
       - asset: assets/fonts/Inter-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Inter-Black.ttf
         weight: 900
        


