// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI66VgHIPQnQdW-ebob3ziycl1A0XKh4E',
    appId: '1:310375535389:web:0c2d3919f5f597d88387f4',
    messagingSenderId: '310375535389',
    projectId: 'rifa-digital-6ae8d',
    authDomain: 'rifa-digital-6ae8d.firebaseapp.com',
    storageBucket: 'rifa-digital-6ae8d.appspot.com',
    measurementId: 'G-TZP4NP7QGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa0vsVEJWIV60cWoQPkSp16LDeGLz8gEE',
    appId: '1:310375535389:android:9414a793d4698a578387f4',
    messagingSenderId: '310375535389',
    projectId: 'rifa-digital-6ae8d',
    storageBucket: 'rifa-digital-6ae8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkH7PqbXCNLTXJPk6peVs8bLy4UuyA2aM',
    appId: '1:310375535389:ios:d5fa5e4c89fccd558387f4',
    messagingSenderId: '310375535389',
    projectId: 'rifa-digital-6ae8d',
    storageBucket: 'rifa-digital-6ae8d.appspot.com',
    androidClientId: '310375535389-a7kcjb4g6aiemd9eeolr4c52rhkvic9n.apps.googleusercontent.com',
    iosClientId: '310375535389-p5jn6hnsnj132kvo8h6u1cjausptb8me.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkH7PqbXCNLTXJPk6peVs8bLy4UuyA2aM',
    appId: '1:310375535389:ios:3729177e35518ba48387f4',
    messagingSenderId: '310375535389',
    projectId: 'rifa-digital-6ae8d',
    storageBucket: 'rifa-digital-6ae8d.appspot.com',
    androidClientId: '310375535389-a7kcjb4g6aiemd9eeolr4c52rhkvic9n.apps.googleusercontent.com',
    iosClientId: '310375535389-pf1gqli7fss4merjin7475c1cttkkm8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstly.RunnerTests',
  );
}
